<?php

namespace App\Services;

use App\Models\Setting;
use Illuminate\Support\Facades\Http;

class RajaOngkirService
{
    protected string $baseUrl = 'https://api.rajaongkir.com/starter';

    protected ?string $apiKey;

    public function __construct()
    {
        $this->apiKey = Setting::getValue('rajaongkir_api_key');
    }

    public function isConfigured(): bool
    {
        return ! empty($this->apiKey);
    }

    public function getCost(int $origin, int $destination, int $weight, string $courier): array
    {
        if (! $this->isConfigured()) {
            return [];
        }

        $response = Http::withHeaders(['key' => $this->apiKey])
            ->post($this->baseUrl.'/cost', [
                'origin' => $origin,
                'destination' => $destination,
                'weight' => $weight,
                'courier' => $courier,
            ]);

        if ($response->failed()) {
            return [];
        }

        $body = $response->json();

        return $body['rajaongkir']['results'] ?? [];
    }

    public function getAllCosts(int $origin, int $destination, int $weight): array
    {
        $couriers = ['jne', 'jnt', 'sicepat', 'ninja'];
        $results = [];

        foreach ($couriers as $courier) {
            $costs = $this->getCost($origin, $destination, $weight, $courier);
            foreach ($costs as $result) {
                $services = [];
                foreach ($result['costs'] as $cost) {
                    $services[$cost['service']] = [
                        'service' => $cost['service'],
                        'description' => $cost['description'],
                        'cost' => $cost['cost'][0]['value'],
                        'etd' => $cost['cost'][0]['etd'] ?? '-',
                    ];
                }
                if (! empty($services)) {
                    $results[$result['code']] = [
                        'name' => $result['name'],
                        'services' => $services,
                    ];
                }
            }
        }

        return $results;
    }

    public function getCourierLabel(string $courier): string
    {
        $labels = [
            'jne' => 'JNE',
            'jnt' => 'J&T',
            'sicepat' => 'SiCepat',
            'ninja' => 'Ninja Express',
        ];

        return $labels[$courier] ?? $courier;
    }

    public function getCities(): array
    {
        if (! $this->isConfigured()) {
            return static::getFallbackCities();
        }

        $cached = cache()->remember('rajaongkir_cities', now()->addDay(), function () {
            $response = Http::withHeaders(['key' => $this->apiKey])
                ->get($this->baseUrl.'/city');

            if ($response->failed()) {
                return null;
            }

            $body = $response->json();
            $cities = $body['rajaongkir']['results'] ?? [];

            return collect($cities)
                ->map(fn ($c) => [
                    'id' => (int) $c['city_id'],
                    'name' => $c['type'].' '.$c['city_name'],
                    'province' => $c['province'],
                ])
                ->sortBy('name')
                ->values()
                ->all();
        });

        if (is_null($cached)) {
            return static::getFallbackCities();
        }

        return $cached;
    }

    public static function getFallbackCities(): array
    {
        return [
            ['id' => 1, 'name' => 'Kabupaten Aceh Barat', 'province' => 'Aceh'],
            ['id' => 2, 'name' => 'Kabupaten Aceh Barat Daya', 'province' => 'Aceh'],
            ['id' => 3, 'name' => 'Kabupaten Aceh Besar', 'province' => 'Aceh'],
            ['id' => 4, 'name' => 'Kabupaten Aceh Jaya', 'province' => 'Aceh'],
            ['id' => 5, 'name' => 'Kabupaten Aceh Selatan', 'province' => 'Aceh'],
            ['id' => 6, 'name' => 'Kabupaten Aceh Singkil', 'province' => 'Aceh'],
            ['id' => 7, 'name' => 'Kabupaten Aceh Tamiang', 'province' => 'Aceh'],
            ['id' => 8, 'name' => 'Kabupaten Aceh Tengah', 'province' => 'Aceh'],
            ['id' => 9, 'name' => 'Kabupaten Aceh Tenggara', 'province' => 'Aceh'],
            ['id' => 10, 'name' => 'Kabupaten Aceh Timur', 'province' => 'Aceh'],
            ['id' => 11, 'name' => 'Kabupaten Aceh Utara', 'province' => 'Aceh'],
            ['id' => 12, 'name' => 'Kota Banda Aceh', 'province' => 'Aceh'],
            ['id' => 13, 'name' => 'Kabupaten Bener Meriah', 'province' => 'Aceh'],
            ['id' => 14, 'name' => 'Kabupaten Bireuen', 'province' => 'Aceh'],
            ['id' => 15, 'name' => 'Kabupaten Gayo Lues', 'province' => 'Aceh'],
            ['id' => 16, 'name' => 'Kota Langsa', 'province' => 'Aceh'],
            ['id' => 17, 'name' => 'Kota Lhokseumawe', 'province' => 'Aceh'],
            ['id' => 18, 'name' => 'Kabupaten Nagan Raya', 'province' => 'Aceh'],
            ['id' => 19, 'name' => 'Kabupaten Pidie', 'province' => 'Aceh'],
            ['id' => 20, 'name' => 'Kabupaten Pidie Jaya', 'province' => 'Aceh'],
            ['id' => 21, 'name' => 'Kota Sabang', 'province' => 'Aceh'],
            ['id' => 22, 'name' => 'Kabupaten Simeulue', 'province' => 'Aceh'],
            ['id' => 23, 'name' => 'Kota Subulussalam', 'province' => 'Aceh'],
            ['id' => 24, 'name' => 'Kota Denpasar', 'province' => 'Bali'],
            ['id' => 25, 'name' => 'Kabupaten Badung', 'province' => 'Bali'],
            ['id' => 26, 'name' => 'Kabupaten Bangli', 'province' => 'Bali'],
            ['id' => 27, 'name' => 'Kabupaten Buleleng', 'province' => 'Bali'],
            ['id' => 28, 'name' => 'Kabupaten Gianyar', 'province' => 'Bali'],
            ['id' => 29, 'name' => 'Kabupaten Jembrana', 'province' => 'Bali'],
            ['id' => 30, 'name' => 'Kabupaten Karangasem', 'province' => 'Bali'],
            ['id' => 31, 'name' => 'Kabupaten Klungkung', 'province' => 'Bali'],
            ['id' => 32, 'name' => 'Kabupaten Tabanan', 'province' => 'Bali'],
            ['id' => 36, 'name' => 'Kota Serang', 'province' => 'Banten'],
            ['id' => 37, 'name' => 'Kabupaten Lebak', 'province' => 'Banten'],
            ['id' => 38, 'name' => 'Kabupaten Pandeglang', 'province' => 'Banten'],
            ['id' => 39, 'name' => 'Kota Cilegon', 'province' => 'Banten'],
            ['id' => 40, 'name' => 'Kabupaten Serang', 'province' => 'Banten'],
            ['id' => 41, 'name' => 'Kabupaten Tangerang', 'province' => 'Banten'],
            ['id' => 42, 'name' => 'Kota Tangerang', 'province' => 'Banten'],
            ['id' => 43, 'name' => 'Kota Tangerang Selatan', 'province' => 'Banten'],
            ['id' => 44, 'name' => 'Kota Bengkulu', 'province' => 'Bengkulu'],
            ['id' => 45, 'name' => 'Kabupaten Bengkulu Selatan', 'province' => 'Bengkulu'],
            ['id' => 46, 'name' => 'Kabupaten Bengkulu Tengah', 'province' => 'Bengkulu'],
            ['id' => 47, 'name' => 'Kabupaten Bengkulu Utara', 'province' => 'Bengkulu'],
            ['id' => 48, 'name' => 'Kabupaten Kaur', 'province' => 'Bengkulu'],
            ['id' => 49, 'name' => 'Kabupaten Kepahiang', 'province' => 'Bengkulu'],
            ['id' => 50, 'name' => 'Kabupaten Lebong', 'province' => 'Bengkulu'],
            ['id' => 51, 'name' => 'Kabupaten Mukomuko', 'province' => 'Bengkulu'],
            ['id' => 52, 'name' => 'Kabupaten Rejang Lebong', 'province' => 'Bengkulu'],
            ['id' => 53, 'name' => 'Kabupaten Seluma', 'province' => 'Bengkulu'],
            ['id' => 54, 'name' => 'Kota Yogyakarta', 'province' => 'DI Yogyakarta'],
            ['id' => 55, 'name' => 'Kabupaten Bantul', 'province' => 'DI Yogyakarta'],
            ['id' => 56, 'name' => 'Kabupaten Gunungkidul', 'province' => 'DI Yogyakarta'],
            ['id' => 57, 'name' => 'Kabupaten Kulon Progo', 'province' => 'DI Yogyakarta'],
            ['id' => 58, 'name' => 'Kabupaten Sleman', 'province' => 'DI Yogyakarta'],
            ['id' => 59, 'name' => 'Kota Gorontalo', 'province' => 'Gorontalo'],
            ['id' => 60, 'name' => 'Kabupaten Boalemo', 'province' => 'Gorontalo'],
            ['id' => 61, 'name' => 'Kabupaten Bone Bolango', 'province' => 'Gorontalo'],
            ['id' => 62, 'name' => 'Kabupaten Gorontalo', 'province' => 'Gorontalo'],
            ['id' => 63, 'name' => 'Kabupaten Gorontalo Utara', 'province' => 'Gorontalo'],
            ['id' => 64, 'name' => 'Kabupaten Pohuwato', 'province' => 'Gorontalo'],
            ['id' => 65, 'name' => 'Kota Jakarta Barat', 'province' => 'DKI Jakarta'],
            ['id' => 66, 'name' => 'Kota Jakarta Pusat', 'province' => 'DKI Jakarta'],
            ['id' => 67, 'name' => 'Kota Jakarta Selatan', 'province' => 'DKI Jakarta'],
            ['id' => 68, 'name' => 'Kota Jakarta Timur', 'province' => 'DKI Jakarta'],
            ['id' => 69, 'name' => 'Kota Jakarta Utara', 'province' => 'DKI Jakarta'],
            ['id' => 70, 'name' => 'Kabupaten Kepulauan Seribu', 'province' => 'DKI Jakarta'],
            ['id' => 71, 'name' => 'Kota Jambi', 'province' => 'Jambi'],
            ['id' => 72, 'name' => 'Kabupaten Batanghari', 'province' => 'Jambi'],
            ['id' => 73, 'name' => 'Kabupaten Bungo', 'province' => 'Jambi'],
            ['id' => 74, 'name' => 'Kabupaten Kerinci', 'province' => 'Jambi'],
            ['id' => 75, 'name' => 'Kabupaten Merangin', 'province' => 'Jambi'],
            ['id' => 76, 'name' => 'Kabupaten Muaro Jambi', 'province' => 'Jambi'],
            ['id' => 77, 'name' => 'Kabupaten Sarolangun', 'province' => 'Jambi'],
            ['id' => 78, 'name' => 'Kabupaten Tanjung Jabung Barat', 'province' => 'Jambi'],
            ['id' => 79, 'name' => 'Kabupaten Tanjung Jabung Timur', 'province' => 'Jambi'],
            ['id' => 80, 'name' => 'Kabupaten Tebo', 'province' => 'Jambi'],
            ['id' => 81, 'name' => 'Kota Bandung', 'province' => 'Jawa Barat'],
            ['id' => 82, 'name' => 'Kota Banjar', 'province' => 'Jawa Barat'],
            ['id' => 83, 'name' => 'Kota Bekasi', 'province' => 'Jawa Barat'],
            ['id' => 84, 'name' => 'Kota Bogor', 'province' => 'Jawa Barat'],
            ['id' => 85, 'name' => 'Kota Cimahi', 'province' => 'Jawa Barat'],
            ['id' => 86, 'name' => 'Kota Cirebon', 'province' => 'Jawa Barat'],
            ['id' => 87, 'name' => 'Kota Depok', 'province' => 'Jawa Barat'],
            ['id' => 88, 'name' => 'Kota Sukabumi', 'province' => 'Jawa Barat'],
            ['id' => 89, 'name' => 'Kota Tasikmalaya', 'province' => 'Jawa Barat'],
            ['id' => 90, 'name' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
            ['id' => 91, 'name' => 'Kabupaten Bandung Barat', 'province' => 'Jawa Barat'],
            ['id' => 92, 'name' => 'Kabupaten Bekasi', 'province' => 'Jawa Barat'],
            ['id' => 93, 'name' => 'Kabupaten Bogor', 'province' => 'Jawa Barat'],
            ['id' => 94, 'name' => 'Kabupaten Ciamis', 'province' => 'Jawa Barat'],
            ['id' => 95, 'name' => 'Kabupaten Cianjur', 'province' => 'Jawa Barat'],
            ['id' => 96, 'name' => 'Kabupaten Cirebon', 'province' => 'Jawa Barat'],
            ['id' => 97, 'name' => 'Kabupaten Garut', 'province' => 'Jawa Barat'],
            ['id' => 98, 'name' => 'Kabupaten Indramayu', 'province' => 'Jawa Barat'],
            ['id' => 99, 'name' => 'Kabupaten Karawang', 'province' => 'Jawa Barat'],
            ['id' => 100, 'name' => 'Kabupaten Kuningan', 'province' => 'Jawa Barat'],
            ['id' => 101, 'name' => 'Kabupaten Majalengka', 'province' => 'Jawa Barat'],
            ['id' => 102, 'name' => 'Kabupaten Pangandaran', 'province' => 'Jawa Barat'],
            ['id' => 103, 'name' => 'Kabupaten Purwakarta', 'province' => 'Jawa Barat'],
            ['id' => 104, 'name' => 'Kabupaten Subang', 'province' => 'Jawa Barat'],
            ['id' => 105, 'name' => 'Kabupaten Sukabumi', 'province' => 'Jawa Barat'],
            ['id' => 106, 'name' => 'Kabupaten Sumedang', 'province' => 'Jawa Barat'],
            ['id' => 107, 'name' => 'Kabupaten Tasikmalaya', 'province' => 'Jawa Barat'],
            ['id' => 108, 'name' => 'Kota Semarang', 'province' => 'Jawa Tengah'],
            ['id' => 109, 'name' => 'Kota Magelang', 'province' => 'Jawa Tengah'],
            ['id' => 110, 'name' => 'Kota Pekalongan', 'province' => 'Jawa Tengah'],
            ['id' => 111, 'name' => 'Kota Salatiga', 'province' => 'Jawa Tengah'],
            ['id' => 112, 'name' => 'Kota Surakarta', 'province' => 'Jawa Tengah'],
            ['id' => 113, 'name' => 'Kota Tegal', 'province' => 'Jawa Tengah'],
            ['id' => 114, 'name' => 'Kabupaten Banjarnegara', 'province' => 'Jawa Tengah'],
            ['id' => 115, 'name' => 'Kabupaten Banyumas', 'province' => 'Jawa Tengah'],
            ['id' => 116, 'name' => 'Kabupaten Batang', 'province' => 'Jawa Tengah'],
            ['id' => 117, 'name' => 'Kabupaten Blora', 'province' => 'Jawa Tengah'],
            ['id' => 118, 'name' => 'Kabupaten Boyolali', 'province' => 'Jawa Tengah'],
            ['id' => 119, 'name' => 'Kabupaten Brebes', 'province' => 'Jawa Tengah'],
            ['id' => 120, 'name' => 'Kabupaten Cilacap', 'province' => 'Jawa Tengah'],
            ['id' => 121, 'name' => 'Kabupaten Demak', 'province' => 'Jawa Tengah'],
            ['id' => 122, 'name' => 'Kabupaten Grobogan', 'province' => 'Jawa Tengah'],
            ['id' => 123, 'name' => 'Kabupaten Jepara', 'province' => 'Jawa Tengah'],
            ['id' => 124, 'name' => 'Kabupaten Karanganyar', 'province' => 'Jawa Tengah'],
            ['id' => 125, 'name' => 'Kabupaten Kebumen', 'province' => 'Jawa Tengah'],
            ['id' => 126, 'name' => 'Kabupaten Kendal', 'province' => 'Jawa Tengah'],
            ['id' => 127, 'name' => 'Kabupaten Klaten', 'province' => 'Jawa Tengah'],
            ['id' => 128, 'name' => 'Kabupaten Kudus', 'province' => 'Jawa Tengah'],
            ['id' => 129, 'name' => 'Kabupaten Magelang', 'province' => 'Jawa Tengah'],
            ['id' => 130, 'name' => 'Kabupaten Pati', 'province' => 'Jawa Tengah'],
            ['id' => 131, 'name' => 'Kabupaten Pekalongan', 'province' => 'Jawa Tengah'],
            ['id' => 132, 'name' => 'Kabupaten Pemalang', 'province' => 'Jawa Tengah'],
            ['id' => 133, 'name' => 'Kabupaten Purbalingga', 'province' => 'Jawa Tengah'],
            ['id' => 134, 'name' => 'Kabupaten Purworejo', 'province' => 'Jawa Tengah'],
            ['id' => 135, 'name' => 'Kabupaten Rembang', 'province' => 'Jawa Tengah'],
            ['id' => 136, 'name' => 'Kabupaten Semarang', 'province' => 'Jawa Tengah'],
            ['id' => 137, 'name' => 'Kabupaten Sragen', 'province' => 'Jawa Tengah'],
            ['id' => 138, 'name' => 'Kabupaten Sukoharjo', 'province' => 'Jawa Tengah'],
            ['id' => 139, 'name' => 'Kabupaten Tegal', 'province' => 'Jawa Tengah'],
            ['id' => 140, 'name' => 'Kabupaten Temanggung', 'province' => 'Jawa Tengah'],
            ['id' => 141, 'name' => 'Kabupaten Wonogiri', 'province' => 'Jawa Tengah'],
            ['id' => 142, 'name' => 'Kabupaten Wonosobo', 'province' => 'Jawa Tengah'],
            ['id' => 143, 'name' => 'Kota Surabaya', 'province' => 'Jawa Timur'],
            ['id' => 144, 'name' => 'Kota Batu', 'province' => 'Jawa Timur'],
            ['id' => 145, 'name' => 'Kota Blitar', 'province' => 'Jawa Timur'],
            ['id' => 146, 'name' => 'Kota Kediri', 'province' => 'Jawa Timur'],
            ['id' => 147, 'name' => 'Kota Madiun', 'province' => 'Jawa Timur'],
            ['id' => 148, 'name' => 'Kota Malang', 'province' => 'Jawa Timur'],
            ['id' => 149, 'name' => 'Kota Mojokerto', 'province' => 'Jawa Timur'],
            ['id' => 150, 'name' => 'Kota Pasuruan', 'province' => 'Jawa Timur'],
            ['id' => 151, 'name' => 'Kota Probolinggo', 'province' => 'Jawa Timur'],
            ['id' => 152, 'name' => 'Kota Jakarta Pusat', 'province' => 'DKI Jakarta'],
            ['id' => 153, 'name' => 'Kabupaten Bangkalan', 'province' => 'Jawa Timur'],
            ['id' => 154, 'name' => 'Kabupaten Banyuwangi', 'province' => 'Jawa Timur'],
            ['id' => 155, 'name' => 'Kabupaten Blitar', 'province' => 'Jawa Timur'],
            ['id' => 156, 'name' => 'Kabupaten Bojonegoro', 'province' => 'Jawa Timur'],
            ['id' => 157, 'name' => 'Kabupaten Bondowoso', 'province' => 'Jawa Timur'],
            ['id' => 158, 'name' => 'Kabupaten Gresik', 'province' => 'Jawa Timur'],
            ['id' => 159, 'name' => 'Kabupaten Jember', 'province' => 'Jawa Timur'],
            ['id' => 160, 'name' => 'Kabupaten Jombang', 'province' => 'Jawa Timur'],
            ['id' => 161, 'name' => 'Kabupaten Kediri', 'province' => 'Jawa Timur'],
            ['id' => 162, 'name' => 'Kabupaten Lamongan', 'province' => 'Jawa Timur'],
            ['id' => 163, 'name' => 'Kabupaten Lumajang', 'province' => 'Jawa Timur'],
            ['id' => 164, 'name' => 'Kabupaten Madiun', 'province' => 'Jawa Timur'],
            ['id' => 165, 'name' => 'Kabupaten Magetan', 'province' => 'Jawa Timur'],
            ['id' => 166, 'name' => 'Kabupaten Malang', 'province' => 'Jawa Timur'],
            ['id' => 167, 'name' => 'Kabupaten Mojokerto', 'province' => 'Jawa Timur'],
            ['id' => 168, 'name' => 'Kabupaten Nganjuk', 'province' => 'Jawa Timur'],
            ['id' => 169, 'name' => 'Kabupaten Ngawi', 'province' => 'Jawa Timur'],
            ['id' => 170, 'name' => 'Kabupaten Pacitan', 'province' => 'Jawa Timur'],
            ['id' => 171, 'name' => 'Kabupaten Pamekasan', 'province' => 'Jawa Timur'],
            ['id' => 172, 'name' => 'Kabupaten Pasuruan', 'province' => 'Jawa Timur'],
            ['id' => 173, 'name' => 'Kabupaten Ponorogo', 'province' => 'Jawa Timur'],
            ['id' => 174, 'name' => 'Kabupaten Probolinggo', 'province' => 'Jawa Timur'],
            ['id' => 175, 'name' => 'Kabupaten Sampang', 'province' => 'Jawa Timur'],
            ['id' => 176, 'name' => 'Kabupaten Sidoarjo', 'province' => 'Jawa Timur'],
            ['id' => 177, 'name' => 'Kabupaten Situbondo', 'province' => 'Jawa Timur'],
            ['id' => 178, 'name' => 'Kabupaten Sumenep', 'province' => 'Jawa Timur'],
            ['id' => 179, 'name' => 'Kabupaten Trenggalek', 'province' => 'Jawa Timur'],
            ['id' => 180, 'name' => 'Kabupaten Tuban', 'province' => 'Jawa Timur'],
            ['id' => 181, 'name' => 'Kabupaten Tulungagung', 'province' => 'Jawa Timur'],
            ['id' => 182, 'name' => 'Kota Pontianak', 'province' => 'Kalimantan Barat'],
            ['id' => 183, 'name' => 'Kabupaten Bengkayang', 'province' => 'Kalimantan Barat'],
            ['id' => 184, 'name' => 'Kabupaten Kapuas Hulu', 'province' => 'Kalimantan Barat'],
            ['id' => 185, 'name' => 'Kabupaten Kayong Utara', 'province' => 'Kalimantan Barat'],
            ['id' => 186, 'name' => 'Kabupaten Ketapang', 'province' => 'Kalimantan Barat'],
            ['id' => 187, 'name' => 'Kabupaten Kubu Raya', 'province' => 'Kalimantan Barat'],
            ['id' => 188, 'name' => 'Kabupaten Landak', 'province' => 'Kalimantan Barat'],
            ['id' => 189, 'name' => 'Kabupaten Melawi', 'province' => 'Kalimantan Barat'],
            ['id' => 190, 'name' => 'Kabupaten Mempawah', 'province' => 'Kalimantan Barat'],
            ['id' => 191, 'name' => 'Kabupaten Sambas', 'province' => 'Kalimantan Barat'],
            ['id' => 192, 'name' => 'Kabupaten Sanggau', 'province' => 'Kalimantan Barat'],
            ['id' => 193, 'name' => 'Kabupaten Sekadau', 'province' => 'Kalimantan Barat'],
            ['id' => 194, 'name' => 'Kabupaten Sintang', 'province' => 'Kalimantan Barat'],
            ['id' => 195, 'name' => 'Kota Banjarmasin', 'province' => 'Kalimantan Selatan'],
            ['id' => 196, 'name' => 'Kota Banjarbaru', 'province' => 'Kalimantan Selatan'],
            ['id' => 197, 'name' => 'Kabupaten Balangan', 'province' => 'Kalimantan Selatan'],
            ['id' => 198, 'name' => 'Kabupaten Banjar', 'province' => 'Kalimantan Selatan'],
            ['id' => 199, 'name' => 'Kabupaten Barito Kuala', 'province' => 'Kalimantan Selatan'],
            ['id' => 200, 'name' => 'Kabupaten Hulu Sungai Selatan', 'province' => 'Kalimantan Selatan'],
            ['id' => 201, 'name' => 'Kabupaten Hulu Sungai Tengah', 'province' => 'Kalimantan Selatan'],
            ['id' => 202, 'name' => 'Kabupaten Hulu Sungai Utara', 'province' => 'Kalimantan Selatan'],
            ['id' => 203, 'name' => 'Kabupaten Kotabaru', 'province' => 'Kalimantan Selatan'],
            ['id' => 204, 'name' => 'Kabupaten Tabalong', 'province' => 'Kalimantan Selatan'],
            ['id' => 205, 'name' => 'Kabupaten Tanah Bumbu', 'province' => 'Kalimantan Selatan'],
            ['id' => 206, 'name' => 'Kabupaten Tanah Laut', 'province' => 'Kalimantan Selatan'],
            ['id' => 207, 'name' => 'Kabupaten Tapin', 'province' => 'Kalimantan Selatan'],
            ['id' => 208, 'name' => 'Kota Palangka Raya', 'province' => 'Kalimantan Tengah'],
            ['id' => 209, 'name' => 'Kabupaten Barito Selatan', 'province' => 'Kalimantan Tengah'],
            ['id' => 210, 'name' => 'Kabupaten Barito Timur', 'province' => 'Kalimantan Tengah'],
            ['id' => 211, 'name' => 'Kabupaten Barito Utara', 'province' => 'Kalimantan Tengah'],
            ['id' => 212, 'name' => 'Kabupaten Gunung Mas', 'province' => 'Kalimantan Tengah'],
            ['id' => 213, 'name' => 'Kabupaten Kapuas', 'province' => 'Kalimantan Tengah'],
            ['id' => 214, 'name' => 'Kabupaten Katingan', 'province' => 'Kalimantan Tengah'],
            ['id' => 215, 'name' => 'Kabupaten Kotawaringin Barat', 'province' => 'Kalimantan Tengah'],
            ['id' => 216, 'name' => 'Kabupaten Kotawaringin Timur', 'province' => 'Kalimantan Tengah'],
            ['id' => 217, 'name' => 'Kabupaten Lamandau', 'province' => 'Kalimantan Tengah'],
            ['id' => 218, 'name' => 'Kabupaten Murung Raya', 'province' => 'Kalimantan Tengah'],
            ['id' => 219, 'name' => 'Kabupaten Pulang Pisau', 'province' => 'Kalimantan Tengah'],
            ['id' => 220, 'name' => 'Kabupaten Seruyan', 'province' => 'Kalimantan Tengah'],
            ['id' => 221, 'name' => 'Kabupaten Sukamara', 'province' => 'Kalimantan Tengah'],
            ['id' => 222, 'name' => 'Kota Samarinda', 'province' => 'Kalimantan Timur'],
            ['id' => 223, 'name' => 'Kota Balikpapan', 'province' => 'Kalimantan Timur'],
            ['id' => 224, 'name' => 'Kota Bontang', 'province' => 'Kalimantan Timur'],
            ['id' => 225, 'name' => 'Kabupaten Berau', 'province' => 'Kalimantan Timur'],
            ['id' => 226, 'name' => 'Kabupaten Kutai Barat', 'province' => 'Kalimantan Timur'],
            ['id' => 227, 'name' => 'Kabupaten Kutai Kartanegara', 'province' => 'Kalimantan Timur'],
            ['id' => 228, 'name' => 'Kabupaten Kutai Timur', 'province' => 'Kalimantan Timur'],
            ['id' => 229, 'name' => 'Kabupaten Mahakam Ulu', 'province' => 'Kalimantan Timur'],
            ['id' => 230, 'name' => 'Kabupaten Paser', 'province' => 'Kalimantan Timur'],
            ['id' => 231, 'name' => 'Kabupaten Penajam Paser Utara', 'province' => 'Kalimantan Timur'],
            ['id' => 232, 'name' => 'Kota Tarakan', 'province' => 'Kalimantan Utara'],
            ['id' => 233, 'name' => 'Kabupaten Bulungan', 'province' => 'Kalimantan Utara'],
            ['id' => 234, 'name' => 'Kabupaten Malinau', 'province' => 'Kalimantan Utara'],
            ['id' => 235, 'name' => 'Kabupaten Nunukan', 'province' => 'Kalimantan Utara'],
            ['id' => 236, 'name' => 'Kabupaten Tana Tidung', 'province' => 'Kalimantan Utara'],
            ['id' => 237, 'name' => 'Kota Pangkal Pinang', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 238, 'name' => 'Kabupaten Bangka', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 239, 'name' => 'Kabupaten Bangka Barat', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 240, 'name' => 'Kabupaten Bangka Selatan', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 241, 'name' => 'Kabupaten Bangka Tengah', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 242, 'name' => 'Kabupaten Belitung', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 243, 'name' => 'Kabupaten Belitung Timur', 'province' => 'Kepulauan Bangka Belitung'],
            ['id' => 244, 'name' => 'Kota Tanjung Pinang', 'province' => 'Kepulauan Riau'],
            ['id' => 245, 'name' => 'Kota Batam', 'province' => 'Kepulauan Riau'],
            ['id' => 246, 'name' => 'Kabupaten Bintan', 'province' => 'Kepulauan Riau'],
            ['id' => 247, 'name' => 'Kabupaten Karimun', 'province' => 'Kepulauan Riau'],
            ['id' => 248, 'name' => 'Kabupaten Kepulauan Anambas', 'province' => 'Kepulauan Riau'],
            ['id' => 249, 'name' => 'Kabupaten Lingga', 'province' => 'Kepulauan Riau'],
            ['id' => 250, 'name' => 'Kabupaten Natuna', 'province' => 'Kepulauan Riau'],
            ['id' => 251, 'name' => 'Kota Bandar Lampung', 'province' => 'Lampung'],
            ['id' => 252, 'name' => 'Kota Metro', 'province' => 'Lampung'],
            ['id' => 253, 'name' => 'Kabupaten Lampung Barat', 'province' => 'Lampung'],
            ['id' => 254, 'name' => 'Kabupaten Lampung Selatan', 'province' => 'Lampung'],
            ['id' => 255, 'name' => 'Kabupaten Lampung Tengah', 'province' => 'Lampung'],
            ['id' => 256, 'name' => 'Kabupaten Lampung Timur', 'province' => 'Lampung'],
            ['id' => 257, 'name' => 'Kabupaten Lampung Utara', 'province' => 'Lampung'],
            ['id' => 258, 'name' => 'Kabupaten Mesuji', 'province' => 'Lampung'],
            ['id' => 259, 'name' => 'Kabupaten Pesawaran', 'province' => 'Lampung'],
            ['id' => 260, 'name' => 'Kabupaten Pesisir Barat', 'province' => 'Lampung'],
            ['id' => 261, 'name' => 'Kabupaten Pringsewu', 'province' => 'Lampung'],
            ['id' => 262, 'name' => 'Kabupaten Tanggamus', 'province' => 'Lampung'],
            ['id' => 263, 'name' => 'Kabupaten Tulang Bawang', 'province' => 'Lampung'],
            ['id' => 264, 'name' => 'Kabupaten Tulang Bawang Barat', 'province' => 'Lampung'],
            ['id' => 265, 'name' => 'Kabupaten Way Kanan', 'province' => 'Lampung'],
            ['id' => 266, 'name' => 'Kota Ambon', 'province' => 'Maluku'],
            ['id' => 267, 'name' => 'Kota Tual', 'province' => 'Maluku'],
            ['id' => 268, 'name' => 'Kabupaten Buru', 'province' => 'Maluku'],
            ['id' => 269, 'name' => 'Kabupaten Buru Selatan', 'province' => 'Maluku'],
            ['id' => 270, 'name' => 'Kabupaten Kepulauan Aru', 'province' => 'Maluku'],
            ['id' => 271, 'name' => 'Kabupaten Maluku Barat Daya', 'province' => 'Maluku'],
            ['id' => 272, 'name' => 'Kabupaten Maluku Tengah', 'province' => 'Maluku'],
            ['id' => 273, 'name' => 'Kabupaten Maluku Tenggara', 'province' => 'Maluku'],
            ['id' => 274, 'name' => 'Kabupaten Maluku Tenggara Barat', 'province' => 'Maluku'],
            ['id' => 275, 'name' => 'Kabupaten Seram Bagian Barat', 'province' => 'Maluku'],
            ['id' => 276, 'name' => 'Kabupaten Seram Bagian Timur', 'province' => 'Maluku'],
            ['id' => 277, 'name' => 'Kota Ternate', 'province' => 'Maluku Utara'],
            ['id' => 278, 'name' => 'Kota Tidore Kepulauan', 'province' => 'Maluku Utara'],
            ['id' => 279, 'name' => 'Kabupaten Halmahera Barat', 'province' => 'Maluku Utara'],
            ['id' => 280, 'name' => 'Kabupaten Halmahera Selatan', 'province' => 'Maluku Utara'],
            ['id' => 281, 'name' => 'Kabupaten Halmahera Tengah', 'province' => 'Maluku Utara'],
            ['id' => 282, 'name' => 'Kabupaten Halmahera Timur', 'province' => 'Maluku Utara'],
            ['id' => 283, 'name' => 'Kabupaten Halmahera Utara', 'province' => 'Maluku Utara'],
            ['id' => 284, 'name' => 'Kabupaten Kepulauan Sula', 'province' => 'Maluku Utara'],
            ['id' => 285, 'name' => 'Kabupaten Pulau Morotai', 'province' => 'Maluku Utara'],
            ['id' => 286, 'name' => 'Kabupaten Pulau Taliabu', 'province' => 'Maluku Utara'],
            ['id' => 287, 'name' => 'Kota Banda Aceh', 'province' => 'Aceh'],
            ['id' => 288, 'name' => 'Kota Mataram', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 289, 'name' => 'Kota Bima', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 290, 'name' => 'Kabupaten Bima', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 291, 'name' => 'Kabupaten Dompu', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 292, 'name' => 'Kabupaten Lombok Barat', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 293, 'name' => 'Kabupaten Lombok Tengah', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 294, 'name' => 'Kabupaten Lombok Timur', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 295, 'name' => 'Kabupaten Lombok Utara', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 296, 'name' => 'Kabupaten Sumbawa', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 297, 'name' => 'Kabupaten Sumbawa Barat', 'province' => 'Nusa Tenggara Barat'],
            ['id' => 298, 'name' => 'Kota Kupang', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 299, 'name' => 'Kabupaten Alor', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 300, 'name' => 'Kabupaten Belu', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 301, 'name' => 'Kabupaten Ende', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 302, 'name' => 'Kabupaten Flores Timur', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 303, 'name' => 'Kabupaten Kupang', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 304, 'name' => 'Kabupaten Lembata', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 305, 'name' => 'Kabupaten Malaka', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 306, 'name' => 'Kabupaten Manggarai', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 307, 'name' => 'Kabupaten Manggarai Barat', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 308, 'name' => 'Kabupaten Manggarai Timur', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 309, 'name' => 'Kabupaten Nagekeo', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 310, 'name' => 'Kabupaten Ngada', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 311, 'name' => 'Kabupaten Rote Ndao', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 312, 'name' => 'Kabupaten Sabu Raijua', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 313, 'name' => 'Kabupaten Sikka', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 314, 'name' => 'Kabupaten Sumba Barat', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 315, 'name' => 'Kabupaten Sumba Barat Daya', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 316, 'name' => 'Kabupaten Sumba Tengah', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 317, 'name' => 'Kabupaten Sumba Timur', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 318, 'name' => 'Kabupaten Timor Tengah Selatan', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 319, 'name' => 'Kabupaten Timor Tengah Utara', 'province' => 'Nusa Tenggara Timur'],
            ['id' => 320, 'name' => 'Kota Jayapura', 'province' => 'Papua'],
            ['id' => 321, 'name' => 'Kabupaten Asmat', 'province' => 'Papua'],
            ['id' => 322, 'name' => 'Kabupaten Biak Numfor', 'province' => 'Papua'],
            ['id' => 323, 'name' => 'Kabupaten Boven Digoel', 'province' => 'Papua'],
            ['id' => 324, 'name' => 'Kabupaten Deiyai', 'province' => 'Papua'],
            ['id' => 325, 'name' => 'Kabupaten Dogiyai', 'province' => 'Papua'],
            ['id' => 326, 'name' => 'Kabupaten Intan Jaya', 'province' => 'Papua'],
            ['id' => 327, 'name' => 'Kabupaten Jayapura', 'province' => 'Papua'],
            ['id' => 328, 'name' => 'Kabupaten Jayawijaya', 'province' => 'Papua'],
            ['id' => 329, 'name' => 'Kabupaten Keerom', 'province' => 'Papua'],
            ['id' => 330, 'name' => 'Kabupaten Kepulauan Yapen', 'province' => 'Papua'],
            ['id' => 331, 'name' => 'Kabupaten Lanny Jaya', 'province' => 'Papua'],
            ['id' => 332, 'name' => 'Kabupaten Mamberamo Raya', 'province' => 'Papua'],
            ['id' => 333, 'name' => 'Kabupaten Mamberamo Tengah', 'province' => 'Papua'],
            ['id' => 334, 'name' => 'Kabupaten Mappi', 'province' => 'Papua'],
            ['id' => 335, 'name' => 'Kabupaten Merauke', 'province' => 'Papua'],
            ['id' => 336, 'name' => 'Kabupaten Mimika', 'province' => 'Papua'],
            ['id' => 337, 'name' => 'Kabupaten Nabire', 'province' => 'Papua'],
            ['id' => 338, 'name' => 'Kabupaten Nduga', 'province' => 'Papua'],
            ['id' => 339, 'name' => 'Kabupaten Paniai', 'province' => 'Papua'],
            ['id' => 340, 'name' => 'Kabupaten Pegunungan Bintang', 'province' => 'Papua'],
            ['id' => 341, 'name' => 'Kabupaten Puncak', 'province' => 'Papua'],
            ['id' => 342, 'name' => 'Kabupaten Puncak Jaya', 'province' => 'Papua'],
            ['id' => 343, 'name' => 'Kabupaten Sarmi', 'province' => 'Papua'],
            ['id' => 344, 'name' => 'Kabupaten Supiori', 'province' => 'Papua'],
            ['id' => 345, 'name' => 'Kabupaten Tolikara', 'province' => 'Papua'],
            ['id' => 346, 'name' => 'Kabupaten Waropen', 'province' => 'Papua'],
            ['id' => 347, 'name' => 'Kabupaten Yahukimo', 'province' => 'Papua'],
            ['id' => 348, 'name' => 'Kabupaten Yalimo', 'province' => 'Papua'],
            ['id' => 349, 'name' => 'Kota Sorong', 'province' => 'Papua Barat Daya'],
            ['id' => 350, 'name' => 'Kabupaten Fakfak', 'province' => 'Papua Barat'],
            ['id' => 351, 'name' => 'Kabupaten Kaimana', 'province' => 'Papua Barat'],
            ['id' => 352, 'name' => 'Kabupaten Manokwari', 'province' => 'Papua Barat'],
            ['id' => 353, 'name' => 'Kabupaten Manokwari Selatan', 'province' => 'Papua Barat'],
            ['id' => 354, 'name' => 'Kabupaten Pegunungan Arfak', 'province' => 'Papua Barat'],
            ['id' => 355, 'name' => 'Kabupaten Sorong', 'province' => 'Papua Barat Daya'],
            ['id' => 356, 'name' => 'Kabupaten Sorong Selatan', 'province' => 'Papua Barat Daya'],
            ['id' => 357, 'name' => 'Kabupaten Tambrauw', 'province' => 'Papua Barat Daya'],
            ['id' => 358, 'name' => 'Kabupaten Teluk Bintuni', 'province' => 'Papua Barat'],
            ['id' => 359, 'name' => 'Kabupaten Teluk Wondama', 'province' => 'Papua Barat'],
            ['id' => 360, 'name' => 'Kota Pekanbaru', 'province' => 'Riau'],
            ['id' => 361, 'name' => 'Kota Dumai', 'province' => 'Riau'],
            ['id' => 362, 'name' => 'Kabupaten Bengkalis', 'province' => 'Riau'],
            ['id' => 363, 'name' => 'Kabupaten Indragiri Hilir', 'province' => 'Riau'],
            ['id' => 364, 'name' => 'Kabupaten Indragiri Hulu', 'province' => 'Riau'],
            ['id' => 365, 'name' => 'Kabupaten Kampar', 'province' => 'Riau'],
            ['id' => 366, 'name' => 'Kabupaten Kepulauan Meranti', 'province' => 'Riau'],
            ['id' => 367, 'name' => 'Kabupaten Kuantan Singingi', 'province' => 'Riau'],
            ['id' => 368, 'name' => 'Kabupaten Pelalawan', 'province' => 'Riau'],
            ['id' => 369, 'name' => 'Kabupaten Rokan Hilir', 'province' => 'Riau'],
            ['id' => 370, 'name' => 'Kabupaten Rokan Hulu', 'province' => 'Riau'],
            ['id' => 371, 'name' => 'Kabupaten Siak', 'province' => 'Riau'],
            ['id' => 372, 'name' => 'Kota Makassar', 'province' => 'Sulawesi Selatan'],
            ['id' => 373, 'name' => 'Kota Palopo', 'province' => 'Sulawesi Selatan'],
            ['id' => 374, 'name' => 'Kota Parepare', 'province' => 'Sulawesi Selatan'],
            ['id' => 375, 'name' => 'Kabupaten Bantaeng', 'province' => 'Sulawesi Selatan'],
            ['id' => 376, 'name' => 'Kabupaten Barru', 'province' => 'Sulawesi Selatan'],
            ['id' => 377, 'name' => 'Kabupaten Bone', 'province' => 'Sulawesi Selatan'],
            ['id' => 378, 'name' => 'Kabupaten Bulukumba', 'province' => 'Sulawesi Selatan'],
            ['id' => 379, 'name' => 'Kabupaten Enrekang', 'province' => 'Sulawesi Selatan'],
            ['id' => 380, 'name' => 'Kabupaten Gowa', 'province' => 'Sulawesi Selatan'],
            ['id' => 381, 'name' => 'Kabupaten Jeneponto', 'province' => 'Sulawesi Selatan'],
            ['id' => 382, 'name' => 'Kabupaten Kepulauan Selayar', 'province' => 'Sulawesi Selatan'],
            ['id' => 383, 'name' => 'Kabupaten Luwu', 'province' => 'Sulawesi Selatan'],
            ['id' => 384, 'name' => 'Kabupaten Luwu Timur', 'province' => 'Sulawesi Selatan'],
            ['id' => 385, 'name' => 'Kabupaten Luwu Utara', 'province' => 'Sulawesi Selatan'],
            ['id' => 386, 'name' => 'Kabupaten Maros', 'province' => 'Sulawesi Selatan'],
            ['id' => 387, 'name' => 'Kabupaten Pangkajene Kepulauan', 'province' => 'Sulawesi Selatan'],
            ['id' => 388, 'name' => 'Kabupaten Pinrang', 'province' => 'Sulawesi Selatan'],
            ['id' => 389, 'name' => 'Kabupaten Sidenreng Rappang', 'province' => 'Sulawesi Selatan'],
            ['id' => 390, 'name' => 'Kabupaten Sinjai', 'province' => 'Sulawesi Selatan'],
            ['id' => 391, 'name' => 'Kabupaten Soppeng', 'province' => 'Sulawesi Selatan'],
            ['id' => 392, 'name' => 'Kabupaten Takalar', 'province' => 'Sulawesi Selatan'],
            ['id' => 393, 'name' => 'Kabupaten Tana Toraja', 'province' => 'Sulawesi Selatan'],
            ['id' => 394, 'name' => 'Kabupaten Toraja Utara', 'province' => 'Sulawesi Selatan'],
            ['id' => 395, 'name' => 'Kabupaten Wajo', 'province' => 'Sulawesi Selatan'],
            ['id' => 396, 'name' => 'Kota Palu', 'province' => 'Sulawesi Tengah'],
            ['id' => 397, 'name' => 'Kabupaten Banggai', 'province' => 'Sulawesi Tengah'],
            ['id' => 398, 'name' => 'Kabupaten Banggai Kepulauan', 'province' => 'Sulawesi Tengah'],
            ['id' => 399, 'name' => 'Kabupaten Banggai Laut', 'province' => 'Sulawesi Tengah'],
            ['id' => 400, 'name' => 'Kabupaten Buol', 'province' => 'Sulawesi Tengah'],
            ['id' => 401, 'name' => 'Kabupaten Donggala', 'province' => 'Sulawesi Tengah'],
            ['id' => 402, 'name' => 'Kabupaten Morowali', 'province' => 'Sulawesi Tengah'],
            ['id' => 403, 'name' => 'Kabupaten Morowali Utara', 'province' => 'Sulawesi Tengah'],
            ['id' => 404, 'name' => 'Kabupaten Parigi Moutong', 'province' => 'Sulawesi Tengah'],
            ['id' => 405, 'name' => 'Kabupaten Poso', 'province' => 'Sulawesi Tengah'],
            ['id' => 406, 'name' => 'Kabupaten Sigi', 'province' => 'Sulawesi Tengah'],
            ['id' => 407, 'name' => 'Kabupaten Tojo Una-Una', 'province' => 'Sulawesi Tengah'],
            ['id' => 408, 'name' => 'Kabupaten Tolitoli', 'province' => 'Sulawesi Tengah'],
            ['id' => 409, 'name' => 'Kota Kendari', 'province' => 'Sulawesi Tenggara'],
            ['id' => 410, 'name' => 'Kota Baubau', 'province' => 'Sulawesi Tenggara'],
            ['id' => 411, 'name' => 'Kabupaten Bombana', 'province' => 'Sulawesi Tenggara'],
            ['id' => 412, 'name' => 'Kabupaten Buton', 'province' => 'Sulawesi Tenggara'],
            ['id' => 413, 'name' => 'Kabupaten Buton Selatan', 'province' => 'Sulawesi Tenggara'],
            ['id' => 414, 'name' => 'Kabupaten Buton Tengah', 'province' => 'Sulawesi Tenggara'],
            ['id' => 415, 'name' => 'Kabupaten Buton Utara', 'province' => 'Sulawesi Tenggara'],
            ['id' => 416, 'name' => 'Kabupaten Kolaka', 'province' => 'Sulawesi Tenggara'],
            ['id' => 417, 'name' => 'Kabupaten Kolaka Timur', 'province' => 'Sulawesi Tenggara'],
            ['id' => 418, 'name' => 'Kabupaten Kolaka Utara', 'province' => 'Sulawesi Tenggara'],
            ['id' => 419, 'name' => 'Kabupaten Konawe', 'province' => 'Sulawesi Tenggara'],
            ['id' => 420, 'name' => 'Kabupaten Konawe Kepulauan', 'province' => 'Sulawesi Tenggara'],
            ['id' => 421, 'name' => 'Kabupaten Konawe Selatan', 'province' => 'Sulawesi Tenggara'],
            ['id' => 422, 'name' => 'Kabupaten Konawe Utara', 'province' => 'Sulawesi Tenggara'],
            ['id' => 423, 'name' => 'Kabupaten Muna', 'province' => 'Sulawesi Tenggara'],
            ['id' => 424, 'name' => 'Kabupaten Muna Barat', 'province' => 'Sulawesi Tenggara'],
            ['id' => 425, 'name' => 'Kabupaten Wakatobi', 'province' => 'Sulawesi Tenggara'],
            ['id' => 426, 'name' => 'Kota Manado', 'province' => 'Sulawesi Utara'],
            ['id' => 427, 'name' => 'Kota Bitung', 'province' => 'Sulawesi Utara'],
            ['id' => 428, 'name' => 'Kota Kotamobagu', 'province' => 'Sulawesi Utara'],
            ['id' => 429, 'name' => 'Kota Tomohon', 'province' => 'Sulawesi Utara'],
            ['id' => 430, 'name' => 'Kabupaten Bolaang Mongondow', 'province' => 'Sulawesi Utara'],
            ['id' => 431, 'name' => 'Kabupaten Bolaang Mongondow Selatan', 'province' => 'Sulawesi Utara'],
            ['id' => 432, 'name' => 'Kabupaten Bolaang Mongondow Timur', 'province' => 'Sulawesi Utara'],
            ['id' => 433, 'name' => 'Kabupaten Bolaang Mongondow Utara', 'province' => 'Sulawesi Utara'],
            ['id' => 434, 'name' => 'Kabupaten Kepulauan Sangihe', 'province' => 'Sulawesi Utara'],
            ['id' => 435, 'name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'province' => 'Sulawesi Utara'],
            ['id' => 436, 'name' => 'Kabupaten Kepulauan Talaud', 'province' => 'Sulawesi Utara'],
            ['id' => 437, 'name' => 'Kabupaten Minahasa', 'province' => 'Sulawesi Utara'],
            ['id' => 438, 'name' => 'Kabupaten Minahasa Selatan', 'province' => 'Sulawesi Utara'],
            ['id' => 439, 'name' => 'Kabupaten Minahasa Tenggara', 'province' => 'Sulawesi Utara'],
            ['id' => 440, 'name' => 'Kabupaten Minahasa Utara', 'province' => 'Sulawesi Utara'],
            ['id' => 441, 'name' => 'Kota Padang', 'province' => 'Sumatera Barat'],
            ['id' => 442, 'name' => 'Kota Bukittinggi', 'province' => 'Sumatera Barat'],
            ['id' => 443, 'name' => 'Kota Padang Panjang', 'province' => 'Sumatera Barat'],
            ['id' => 444, 'name' => 'Kota Pariaman', 'province' => 'Sumatera Barat'],
            ['id' => 445, 'name' => 'Kota Payakumbuh', 'province' => 'Sumatera Barat'],
            ['id' => 446, 'name' => 'Kota Sawahlunto', 'province' => 'Sumatera Barat'],
            ['id' => 447, 'name' => 'Kota Solok', 'province' => 'Sumatera Barat'],
            ['id' => 448, 'name' => 'Kabupaten Agam', 'province' => 'Sumatera Barat'],
            ['id' => 449, 'name' => 'Kabupaten Dharmasraya', 'province' => 'Sumatera Barat'],
            ['id' => 450, 'name' => 'Kabupaten Kepulauan Mentawai', 'province' => 'Sumatera Barat'],
            ['id' => 451, 'name' => 'Kabupaten Lima Puluh Kota', 'province' => 'Sumatera Barat'],
            ['id' => 452, 'name' => 'Kabupaten Padang Pariaman', 'province' => 'Sumatera Barat'],
            ['id' => 453, 'name' => 'Kabupaten Pasaman', 'province' => 'Sumatera Barat'],
            ['id' => 454, 'name' => 'Kabupaten Pasaman Barat', 'province' => 'Sumatera Barat'],
            ['id' => 455, 'name' => 'Kabupaten Pesisir Selatan', 'province' => 'Sumatera Barat'],
            ['id' => 456, 'name' => 'Kabupaten Sijunjung', 'province' => 'Sumatera Barat'],
            ['id' => 457, 'name' => 'Kabupaten Solok', 'province' => 'Sumatera Barat'],
            ['id' => 458, 'name' => 'Kabupaten Solok Selatan', 'province' => 'Sumatera Barat'],
            ['id' => 459, 'name' => 'Kabupaten Tanah Datar', 'province' => 'Sumatera Barat'],
            ['id' => 460, 'name' => 'Kota Palembang', 'province' => 'Sumatera Selatan'],
            ['id' => 461, 'name' => 'Kota Lubuklinggau', 'province' => 'Sumatera Selatan'],
            ['id' => 462, 'name' => 'Kota Pagar Alam', 'province' => 'Sumatera Selatan'],
            ['id' => 463, 'name' => 'Kota Prabumulih', 'province' => 'Sumatera Selatan'],
            ['id' => 464, 'name' => 'Kabupaten Banyuasin', 'province' => 'Sumatera Selatan'],
            ['id' => 465, 'name' => 'Kabupaten Empat Lawang', 'province' => 'Sumatera Selatan'],
            ['id' => 466, 'name' => 'Kabupaten Lahat', 'province' => 'Sumatera Selatan'],
            ['id' => 467, 'name' => 'Kabupaten Muara Enim', 'province' => 'Sumatera Selatan'],
            ['id' => 468, 'name' => 'Kabupaten Musi Banyuasin', 'province' => 'Sumatera Selatan'],
            ['id' => 469, 'name' => 'Kabupaten Musi Rawas', 'province' => 'Sumatera Selatan'],
            ['id' => 470, 'name' => 'Kabupaten Musi Rawas Utara', 'province' => 'Sumatera Selatan'],
            ['id' => 471, 'name' => 'Kabupaten Ogan Ilir', 'province' => 'Sumatera Selatan'],
            ['id' => 472, 'name' => 'Kabupaten Ogan Komering Ilir', 'province' => 'Sumatera Selatan'],
            ['id' => 473, 'name' => 'Kabupaten Ogan Komering Ulu', 'province' => 'Sumatera Selatan'],
            ['id' => 474, 'name' => 'Kabupaten Ogan Komering Ulu Selatan', 'province' => 'Sumatera Selatan'],
            ['id' => 475, 'name' => 'Kabupaten Ogan Komering Ulu Timur', 'province' => 'Sumatera Selatan'],
            ['id' => 476, 'name' => 'Kabupaten Penukal Abab Lematang Ilir', 'province' => 'Sumatera Selatan'],
            ['id' => 477, 'name' => 'Kota Medan', 'province' => 'Sumatera Utara'],
            ['id' => 478, 'name' => 'Kota Binjai', 'province' => 'Sumatera Utara'],
            ['id' => 479, 'name' => 'Kota Gunungsitoli', 'province' => 'Sumatera Utara'],
            ['id' => 480, 'name' => 'Kota Padangsidimpuan', 'province' => 'Sumatera Utara'],
            ['id' => 481, 'name' => 'Kota Pematangsiantar', 'province' => 'Sumatera Utara'],
            ['id' => 482, 'name' => 'Kota Sibolga', 'province' => 'Sumatera Utara'],
            ['id' => 483, 'name' => 'Kota Tanjungbalai', 'province' => 'Sumatera Utara'],
            ['id' => 484, 'name' => 'Kota Tebing Tinggi', 'province' => 'Sumatera Utara'],
            ['id' => 485, 'name' => 'Kabupaten Asahan', 'province' => 'Sumatera Utara'],
            ['id' => 486, 'name' => 'Kabupaten Batu Bara', 'province' => 'Sumatera Utara'],
            ['id' => 487, 'name' => 'Kabupaten Dairi', 'province' => 'Sumatera Utara'],
            ['id' => 488, 'name' => 'Kabupaten Deli Serdang', 'province' => 'Sumatera Utara'],
            ['id' => 489, 'name' => 'Kabupaten Humbang Hasundutan', 'province' => 'Sumatera Utara'],
            ['id' => 490, 'name' => 'Kabupaten Karo', 'province' => 'Sumatera Utara'],
            ['id' => 491, 'name' => 'Kabupaten Labuhanbatu', 'province' => 'Sumatera Utara'],
            ['id' => 492, 'name' => 'Kabupaten Labuhanbatu Selatan', 'province' => 'Sumatera Utara'],
            ['id' => 493, 'name' => 'Kabupaten Labuhanbatu Utara', 'province' => 'Sumatera Utara'],
            ['id' => 494, 'name' => 'Kabupaten Langkat', 'province' => 'Sumatera Utara'],
            ['id' => 495, 'name' => 'Kabupaten Mandailing Natal', 'province' => 'Sumatera Utara'],
            ['id' => 496, 'name' => 'Kabupaten Nias', 'province' => 'Sumatera Utara'],
            ['id' => 497, 'name' => 'Kabupaten Nias Barat', 'province' => 'Sumatera Utara'],
            ['id' => 498, 'name' => 'Kabupaten Nias Selatan', 'province' => 'Sumatera Utara'],
            ['id' => 499, 'name' => 'Kabupaten Nias Utara', 'province' => 'Sumatera Utara'],
            ['id' => 500, 'name' => 'Kabupaten Padang Lawas', 'province' => 'Sumatera Utara'],
            ['id' => 501, 'name' => 'Kabupaten Padang Lawas Utara', 'province' => 'Sumatera Utara'],
            ['id' => 502, 'name' => 'Kabupaten Pakpak Bharat', 'province' => 'Sumatera Utara'],
            ['id' => 503, 'name' => 'Kabupaten Samosir', 'province' => 'Sumatera Utara'],
            ['id' => 504, 'name' => 'Kabupaten Serdang Bedagai', 'province' => 'Sumatera Utara'],
            ['id' => 505, 'name' => 'Kabupaten Simalungun', 'province' => 'Sumatera Utara'],
            ['id' => 506, 'name' => 'Kabupaten Tapanuli Selatan', 'province' => 'Sumatera Utara'],
            ['id' => 507, 'name' => 'Kabupaten Tapanuli Tengah', 'province' => 'Sumatera Utara'],
            ['id' => 508, 'name' => 'Kabupaten Tapanuli Utara', 'province' => 'Sumatera Utara'],
            ['id' => 509, 'name' => 'Kabupaten Toba', 'province' => 'Sumatera Utara'],
        ];
    }
}
